LANGUAGES = {
    "en": {
        "STATION STATUS": "STATION STATUS",
        "SET TARGET WEIGHT": "SET TARGET WEIGHT",
        "SET TIME LIMIT": "SET TIME LIMIT",
        "SET LANGUAGE": "SET LANGUAGE",
        "CHANGE UNITS": "CHANGE UNITS",
        "EXIT": "EXIT",
        "CALIBRATION_TITLE": "CALIBRATION",
        "CALIBRATION_REMOVE_WEIGHT": "REMOVE ALL WEIGHT FROM THE SCALE\n\nPRESS SELECT WHEN READY",
        "CALIBRATION_COMPLETE_TITLE": "CALIBRATION COMPLETE",
        "CALIBRATION_COMPLETE_MSG": "NEW CALIBRATION VALUE SAVED: {value}\n\nPRESS SELECT TO FINISH",
        "CALIBRATION_PLACE_WEIGHT": "PLACE A WEIGHT ON THE SCALE AND SET THE VALUE\n\nCALIBRATION WEIGHT: {value} G\n\nUSE UP/DOWN TO ADJUST.\nPRESS SELECT WHEN READY.",
        "CALIBRATION_CALCULATING": "CALCULATING RATIO...",
        "CLEAR_SCALES_TITLE": "CLEAR SCALES",
        "CLEAR_SCALES_MSG": "PRESS SELECT WHEN READY",
        "SCALES_RESET_TITLE": "SCALES RESET",
        "SCALES_RESET_MSG": "",
        "ESTOP_TITLE": "E-STOP ACTIVATED",
        "ESTOP_MSG": "\n\nRESET TO CONTINUE.",
        "FILL_COMPLETE_TITLE": "FILL COMPLETE:",
        "TIME_LIMIT_REACHED_TITLE": "TIME LIMIT REACHED:",
        "TIME_LABEL": "TIME",
        "WEIGHT_LABEL": "WEIGHT",
        "FINAL_WEIGHT": "Final: {}",
        "FILL_TIME": "Fill Time: {} ms",
        "STATION_OFFLINE": "STATION OFFLINE",
        "STATION": "STATION",
        "ENABLED": "ENABLED",
        "DISABLED": "DISABLED",
        "FILLING MODE": "FILLING MODE",
        "SET FILLING MODE": "SET FILLING MODE",
        "AUTO": "AUTO",
        "MANUAL": "MANUAL",
        "AUTO FILL RUNNING": "AUTO FILL RUNNING",
        "AUTO FILL READY": "AUTO FILL READY",
        "FINAL WEIGHT": "FINAL WEIGHT",
        "TIME": "TIME",
        "SMART": "SMART",
        "CONNECTED": "CONNECTED",
        "DISCONNECTED": "DISCONNECTED",
        "TARGET WEIGHT SAVED:": "TARGET WEIGHT SAVED:",
        "TIME LIMIT SAVED:": "TIME LIMIT SAVED:",
        "ERROR": "ERROR",
        "MAX WEIGHT EXCEEDED": "MAX WEIGHT EXCEEDED",
        "MAX WEIGHT CLEARED": "MAX WEIGHT CLEARED",
        "ACCEPT": "ACCEPT",
        "PRESS SELECT TO CONTINUE": "PRESS SELECT TO CONTINUE",
        "ENTER_NEW_TARGET_WEIGHT": "ENTER NEW TARGET WEIGHT",
        "ENTER_NEW_TIME_LIMIT": "ENTER NEW TIME LIMIT",
        "Grams": "Grams",
        "Ounces": "Ounces",
        "English": "English",
        "Español": "Español",
        "READY": "READY",
        "TIMEOUT": "TIMEOUT",
    "BACK": "BACK",
    "SHUT DOWN": "SHUT DOWN",
    "CONFIRM": "CONFIRM",
    "Manual Mode Selected": "Manual Mode Selected",
    "Manual mode selected. You will control filling manually.": "Manual mode selected. You will control filling manually.",
    "Auto Mode": "Auto Mode",
    "Manual Mode": "Manual Mode",
    "Smart Mode": "Smart Mode",
    "Confirm All Scales Are Clear": "Confirm All Scales Are Clear",
    "Station {num}": "Station {num}",
    "--": "--",
    "0.0 g": "0.0 g",
    "oz": "oz",
    "g": "g",
    "No stations connected": "No stations connected",
    "No stations enabled": "No stations enabled",
    "No bottles detected": "No bottles detected",
    "Please place empty bottles": "Please place empty bottles",
    "Please place full bottles": "Please place full bottles",
    "Selection Required": "Selection Required",
    "Continue": "Continue",
    "Cancel": "Cancel",
    "Station verification": "Station verification",
    "Calibration": "Calibration",
    "Filling": "Filling",
    "Fill locked": "Fill locked",
    "Fill request rejected": "Fill request rejected",
    "Fill request accepted": "Fill request accepted",
    "Fill started": "Fill started",
    "Fill completed": "Fill completed",
    "Fill timed out": "Fill timed out",
    "Fill stopped": "Fill stopped",
    "Fill error": "Fill error",
    "Fill warning": "Fill warning",
    "Fill info": "Fill info",
    "Fill status": "Fill status",
    "Fill time": "Fill time",
    "Fill weight": "Fill weight",
    "Fill mode": "Fill mode",
    "Fill result": "Fill result",
    "Fill limit": "Fill limit",
    "Fill range": "Fill range",
    "Fill bottle": "Fill bottle",
    "Fill station": "Fill station",
    "Fill value": "Fill value",
    "Fill target": "Fill target",
    "Fill actual": "Fill actual",
    "Fill difference": "Fill difference",
    "Fill tolerance": "Fill tolerance",
    "Fill calibration": "Fill calibration",
    "Fill prompt": "Fill prompt",
    "Fill selection": "Fill selection",
    "Fill dialog": "Fill dialog",
    "Fill overlay": "Fill overlay",
    "Fill button": "Fill button",
    "Fill column": "Fill column",
    "Fill widget": "Fill widget",
    "Fill app": "Fill app",
    "Fill event": "Fill event",
    "Fill error log": "Fill error log",
    "Fill info dialog": "Fill info dialog",
    "Fill status dialog": "Fill status dialog",
    "Fill station dialog": "Fill station dialog",
    "Fill bottle dialog": "Fill bottle dialog",
    "Fill calibration dialog": "Fill calibration dialog",
    "Fill prompt dialog": "Fill prompt dialog",
    "Fill selection dialog": "Fill selection dialog",
    "Fill overlay dialog": "Fill overlay dialog",
    "Fill button dialog": "Fill button dialog",
    "Fill column dialog": "Fill column dialog",
    "Fill widget dialog": "Fill widget dialog",
    "Fill app dialog": "Fill app dialog",
    "Fill event dialog": "Fill event dialog",
    "Fill error log dialog": "Fill error log dialog"
    },
    "es": {
        "STATION STATUS": "ESTADO DE ESTACIÓN",
        "SET TARGET WEIGHT": "FIJAR PESO OBJETIVO",
        "SET TIME LIMIT": "FIJAR LÍMITE DE TIEMPO",
    "AUTO FILL RUNNING": "LLENADO AUTOMÁTICO EN PROGRESO",
    "AUTO FILL READY": "LLENADO AUTOMÁTICO LISTO",
    "FINAL WEIGHT": "PESO FINAL",
    "TIME": "TIEMPO",
        "SET LANGUAGE": "CAMBIAR IDIOMA",
        "CHANGE UNITS": "CAMBIAR UNIDADES",
        "EXIT": "SALIR",
        "CALIBRATION_TITLE": "CALIBRACIÓN",
        "CALIBRATION_REMOVE_WEIGHT": "RETIRA TODO EL PESO DE LA BALANZA\n\nPULSA SELECT CUANDO ESTÉ LISTO",
        "CALIBRATION_COMPLETE_TITLE": "CALIBRACIÓN COMPLETA",
        "CALIBRATION_COMPLETE_MSG": "NUEVO VALOR DE CALIBRACIÓN GUARDADO: {value}\n\nPULSA SELECT PARA FINALIZAR",
        "CALIBRATION_PLACE_WEIGHT": "COLOCA UN PESO EN LA BALANZA Y AJUSTA EL VALOR\n\nPESO DE CALIBRACIÓN: {value} G\n\nUSA ARRIBA/ABAJO PARA AJUSTAR.\nPULSA SELECT CUANDO ESTÉ LISTO.",
        "CALIBRATION_CALCULATING": "CALCULANDO RELACIÓN...",
        "CLEAR_SCALES_TITLE": "LIMPIAR BALANZAS",
        "CLEAR_SCALES_MSG": "PULSA SELECT CUANDO ESTÉ LISTO",
        "SCALES_RESET_TITLE": "BALANZAS REINICIADAS",
        "SCALES_RESET_MSG": "",
        "ESTOP_TITLE": "PARADA DE EMERGENCIA",
        "ESTOP_MSG": "\n\nRESET PARA CONTINUAR.",
        "FILL_COMPLETE_TITLE": "LLENADO COMPLETO:",
        "TIME_LIMIT_REACHED_TITLE": "SE ALCANZÓ EL LÍMITE DE TIEMPO:",
        "TIME_LABEL": "TIEMPO",
        "WEIGHT_LABEL": "PESO",
        "STATION": "ESTACIÓN",
        "ENABLED": "HABILITADO",
        "DISABLED": "DESHABILITADO",        
        "STATION_OFFLINE": "FUERA DE SERVICIO",
        "FINAL_WEIGHT": "FINAL: {}",
        "FILL_TIME": "TIEMPO DE LLENADO: {} ms",
        "FILLING MODE": "MODO DE LLENADO",
        "SET FILLING MODE": "FIJAR MODO DE LLENADO",
        "AUTO": "AUTO",
        "MANUAL": "MANUAL",
        "SMART": "INTELIGENTE",
        "CONNECTED": "CONECTADO",
        "DISCONNECTED": "DESCONECTADO",
        "TARGET WEIGHT SAVED:": "PESO OBJETIVO GUARDADO:",
        "TIME LIMIT SAVED:": "LÍMITE DE TIEMPO GUARDADO:",
        "ERROR": "ERROR",
        "MAX WEIGHT EXCEEDED": "PESO MÁXIMO EXCEDIDO",
        "MAX WEIGHT CLEARED": "PESO MÁXIMO RESTABLECIDO",
        "ACCEPT": "ACEPTAR",
        "PRESS SELECT TO CONTINUE": "PULSA SELECT PARA CONTINUAR",
        "ENTER_NEW_TARGET_WEIGHT": "INTRODUCE NUEVO PESO OBJETIVO",
        "ENTER_NEW_TIME_LIMIT": "INTRODUCE NUEVO LÍMITE DE TIEMPO",
        "Grams": "Gramos",
        "Ounces": "Onzas",
        "English": "Inglés",
        "Español": "Español",
        "READY": "LISTO",
        "TIMEOUT": "TIEMPO AGOTADO",
    "BACK": "ATRÁS",
    "SHUT DOWN": "APAGAR",
    "CONFIRM": "CONFIRMAR",
    "Manual Mode Selected": "Modo manual seleccionado",
    "Manual mode selected. You will control filling manually.": "Modo manual seleccionado. Controlarás el llenado manualmente.",
    "Auto Mode": "Modo automático",
    "Manual Mode": "Modo manual",
    "Smart Mode": "Modo inteligente",
    "Confirm All Scales Are Clear": "Confirma que todas las balanzas están limpias",
    "Station {num}": "Estación {num}",
    "--": "--",
    "0.0 g": "0.0 g",
    "oz": "oz",
    "g": "g",
    "No stations connected": "Ninguna estación conectada",
    "No stations enabled": "Ninguna estación habilitada",
    "No bottles detected": "No se detectaron botellas",
    "Please place empty bottles": "Por favor coloca botellas vacías",
    "Please place full bottles": "Por favor coloca botellas llenas",
    "Selection Required": "Selección requerida",
    "Continue": "Continuar",
    "Cancel": "Cancelar",
    "Station verification": "Verificación de estación",
    "Calibration": "Calibración",
    "Filling": "Llenado",
    "Fill locked": "Llenado bloqueado",
    "Fill request rejected": "Solicitud de llenado rechazada",
    "Fill request accepted": "Solicitud de llenado aceptada",
    "Fill started": "Llenado iniciado",
    "Fill completed": "Llenado completado",
    "Fill timed out": "Llenado agotado",
    "Fill stopped": "Llenado detenido",
    "Fill error": "Error de llenado",
    "Fill warning": "Advertencia de llenado",
    "Fill info": "Información de llenado",
    "Fill status": "Estado de llenado",
    "Fill time": "Tiempo de llenado",
    "Fill weight": "Peso de llenado",
    "Fill mode": "Modo de llenado",
    "Fill result": "Resultado de llenado",
    "Fill limit": "Límite de llenado",
    "Fill range": "Rango de llenado",
    "Fill bottle": "Botella de llenado",
    "Fill station": "Estación de llenado",
    "Fill value": "Valor de llenado",
    "Fill target": "Objetivo de llenado",
    "Fill actual": "Actual de llenado",
    "Fill difference": "Diferencia de llenado",
    "Fill tolerance": "Tolerancia de llenado",
    "Fill calibration": "Calibración de llenado",
    "Fill prompt": "Mensaje de llenado",
    "Fill selection": "Selección de llenado",
    "Fill dialog": "Diálogo de llenado",
    "Fill overlay": "Superposición de llenado",
    "Fill button": "Botón de llenado",
    "Fill column": "Columna de llenado",
    "Fill widget": "Widget de llenado",
    "Fill app": "App de llenado",
    "Fill event": "Evento de llenado",
    "Fill error log": "Registro de errores de llenado",
    "Fill info dialog": "Diálogo de información de llenado",
    "Fill status dialog": "Diálogo de estado de llenado",
    "Fill station dialog": "Diálogo de estación de llenado",
    "Fill bottle dialog": "Diálogo de botella de llenado",
    "Fill calibration dialog": "Diálogo de calibración de llenado",
    "Fill prompt dialog": "Diálogo de mensaje de llenado",
    "Fill selection dialog": "Diálogo de selección de llenado",
    "Fill overlay dialog": "Diálogo de superposición de llenado",
    "Fill button dialog": "Diálogo de botón de llenado",
    "Fill column dialog": "Diálogo de columna de llenado",
    "Fill widget dialog": "Diálogo de widget de llenado",
    "Fill app dialog": "Diálogo de app de llenado",
    "Fill event dialog": "Diálogo de evento de llenado",
    "Fill error log dialog": "Diálogo de registro de errores de llenado"
    }
}