LANGUAGES = {
    "en": {
        "SET_TARGET_WEIGHT_TITLE": "SET TARGET WEIGHT",
        "SET_TARGET_WEIGHT_MSG": "Use UP/DOWN buttons to adjust.\nPress SELECT to confirm.",
        "ENTER_NEW_TARGET_WEIGHT": "Enter new target weight:",
        "SET_TIME_LIMIT_TITLE": "SET TIME LIMIT",
        "SET_TIME_LIMIT_MSG": "Use UP/DOWN buttons to adjust.\nPress SELECT to confirm.",
        "ENTER_NEW_TIME_LIMIT": "Enter new time limit:",
        "SET_LANGUAGE_TITLE": "SET LANGUAGE",
        "CHOOSE_LANGUAGE": "Choose language:",
        "CHANGE_UNITS_TITLE": "CHANGE UNITS",
        "CHOOSE_UNITS": "Choose units:",
        "EXIT": "Exit",
        "CALIBRATION_TITLE": "Calibration",
        "CALIBRATION_REMOVE_WEIGHT": "Remove all weight from the scale\n\nPress SELECT when ready",
        "CALIBRATION_COMPLETE_TITLE": "Calibration Complete",
        "CALIBRATION_COMPLETE_MSG": "New calibration value saved: {value}\n\nPress SELECT to finish",
        "CALIBRATION_PLACE_WEIGHT": "Place a weight on the scale and set the value\n\nCalibration Weight: {value} g\n\nUse UP/DOWN to adjust.\nPress SELECT when ready.",
        "CALIBRATION_CALCULATING": "Calculating ratio...",
        "CLEAR_SCALES_TITLE": "CLEAR SCALES",
        "CLEAR_SCALES_MSG": "PRESS SELECT WHEN READY",
        "SCALES_RESET_TITLE": "SCALES RESET",
        "SCALES_RESET_MSG": "",
        "ESTOP_TITLE": "E-STOP ACTIVATED",
        "ESTOP_MSG": "\n\nRESET to continue.",
        "FILL_COMPLETE_TITLE": "FILL COMPLETE:",
        "TIME_LIMIT_REACHED_TITLE": "TIME LIMIT REACHED:",
        "TIME_LABEL": "Time",
        "WEIGHT_LABEL": "Weight",
        # Add more as needed...
    },
    "es": {
        "SET_TARGET_WEIGHT_TITLE": "FIJAR PESO OBJETIVO",
        "SET_TARGET_WEIGHT_MSG": "Usa los botones ARRIBA/ABAJO para ajustar.\nPulsa SELECT para confirmar.",
        "ENTER_NEW_TARGET_WEIGHT": "Introduce el nuevo peso objetivo:",
        "SET_TIME_LIMIT_TITLE": "FIJAR LÍMITE DE TIEMPO",
        "SET_TIME_LIMIT_MSG": "Usa los botones ARRIBA/ABAJO para ajustar.\nPulsa SELECT para confirmar.",
        "ENTER_NEW_TIME_LIMIT": "Introduce el nuevo límite de tiempo:",
        "SET_LANGUAGE_TITLE": "FIJAR IDIOMA",
        "CHOOSE_LANGUAGE": "Elige idioma:",
        "CHANGE_UNITS_TITLE": "CAMBIAR UNIDADES",
        "CHOOSE_UNITS": "Elige unidades:",
        "EXIT": "Salir",
        "CALIBRATION_TITLE": "Calibración",
        "CALIBRATION_REMOVE_WEIGHT": "Retira todo el peso de la balanza\n\nPulsa SELECT cuando esté listo",
        "CALIBRATION_COMPLETE_TITLE": "Calibración Completa",
        "CALIBRATION_COMPLETE_MSG": "Nuevo valor de calibración guardado: {value}\n\nPulsa SELECT para finalizar",
        "CALIBRATION_PLACE_WEIGHT": "Coloca un peso en la balanza y ajusta el valor\n\nPeso de calibración: {value} g\n\nUsa ARRIBA/ABAJO para ajustar.\nPulsa SELECT cuando esté listo.",
        "CALIBRATION_CALCULATING": "Calculando relación...",
        "CLEAR_SCALES_TITLE": "LIMPIAR BALANZAS",
        "CLEAR_SCALES_MSG": "PULSA SELECT CUANDO ESTÉ LISTO",
        "SCALES_RESET_TITLE": "BALANZAS REINICIADAS",
        "SCALES_RESET_MSG": "",
        "ESTOP_TITLE": "PARADA DE EMERGENCIA",
        "ESTOP_MSG": "\n\nRESET para continuar.",
        "FILL_COMPLETE_TITLE": "LLENADO COMPLETO:",
        "TIME_LIMIT_REACHED_TITLE": "SE ALCANZÓ EL LÍMITE DE TIEMPO:",
        "TIME_LABEL": "Tiempo",
        "WEIGHT_LABEL": "Peso",
    }
}